services:
  frontend:
    image: frontend:dev
    environment:
      PORT: 3000
    ports:
      - 3000:3000
  calculator-api:
    image: calc-api:latest
    environment:
      PORT: 8080
    ports:
      - 8080:8080
