name: Backend Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Backend Docker image
      run: docker build . --file ./calculator-api/Dockerfile --tag calc-api:$(date +%s)
