name: Front End Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        dockerfile: ./frontend/Dockerfile
    - name: Build the Front End Docker image
      run: docker build . --file Dockerfile --tag frontend-calc:$(date +%s)
