name: Front End Docker Image CD

on:
  release:
    types: [published]

jobs:

  push_to_registry:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & push the Frontend Docker image
      uses: docker/build-push-action@v2
#       run: docker build . --file ./calculator-api/Dockerfile --tag calc-api:$(date +%s)
      with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/frontend:${{ github.sha }}
